"""
GUIDIO - Dictionary untuk fitur Open-Vocabulary Object Detection (YOLOE)
=========================================================================
Berisi tiga dictionary utama:
1. COLOR_MAP           -> pemetaan warna/nuansa/pola ID -> EN
2. EXTRA_ID_TO_EN       -> pemetaan nama objek ID -> prompt class EN
3. EXTRA_HEIGHTS_CM     -> estimasi tinggi fisik objek (cm) untuk
                           similar-triangle distance estimation
"""

# =========================================================================
# 0. SEARCH_PREFIXES & FILLER_WORDS (Pembersih Perintah Suara)
# =========================================================================
SEARCH_PREFIXES: set[str] = {
    # --- Bentuk berimbuhan me- (baku) ---
    # Pernah hilang seluruhnya dari daftar ini maupun dari kembarannya di
    # aplikasi (`CommandParser.searchPrefixes`). Akibatnya di aplikasi jauh
    # lebih parah - "saya mau mencari botol" tidak dikenali sebagai perintah
    # mencari sama sekali - tapi di sini pun bocornya nyata: kata "mencari"
    # ikut terbawa ke `resolve_prompt` dan berakhir di prompt YOLOE.
    "mencari", "mencarikan", "menemukan", "mencari-cari", "menyari",
    "nemuin", "nemu", "ketemuin",
    "mau cari", "mau mencari", "mau nyari", "ingin cari", "ingin mencari",
    "pengen cari", "pengen mencari", "pengen nyari", "pingin cari",
    "lagi mencari", "sedang mencari", "butuh cari",
    "cari", "carikan", "carilah", "tolong cari", "tolong carikan", "mohon cari",
    "mohon carikan", "bantu cari", "bantu carikan", "coba cari", "coba carikan",
    "silakan cari", "silakan carikan", "temukan", "temuin", "tunjukin", "tunjukkan",
    "deteksi", "scan", "pindai", "cariin", "cariin dong", "cariin deh", "cariin dong ya",
    "cariin napa", "cariin woy", "cariin bentar", "cariin sini", "cariin cepetan",
    "tolong cariin", "tolong cariin dong", "tolong cariin ya", "bantu cariin",
    "bantu cariin dong", "bantuin cari", "bantuin cariin", "bantuin dong cariin",
    "bantuin nyari", "bantu nemuin", "tolong temuin", "gan cariin", "bro cariin",
    "woy cariin", "eh cariin", "nyari", "nyariin", "nyari-nyari", "lagi nyari",
    "lagi nyariin", "lagi cariin", "kehilangan", "saya kehilangan", "aku kehilangan",
    "hilang", "ilang", "kemana", "ke mana", "dimana", "di mana", "dimanakah",
    "di manakah", "mana", "ada dimana", "gue kehilangan", "gua kehilangan",
    "ane kehilangan", "gw kehilangan", "ilangan", "ngilang", "kemana ya", "kemana sih",
    "mana ya", "mana sih", "mana nih", "kaga ketemu", "kagak ketemu", "gak ketemu",
    "ga ketemu", "nggak ketemu", "tidak ketemu", "belum ketemu", "susah nemu",
    "ga nemu", "gak nemu", "gak nemu-nemu", "gak bisa nemu", "kok gak ada ya",
    "kok hilang ya", "tadi taruh dimana ya", "ilang kemana ini",
    # Bahasa Daerah
    "ilang kemane", "digoleki", "goleki", "ora ono", "ilang neng ndi", "diteangan",
    "milarian", "leungit dimana", "ilang kama", "ilang dima", "dima yo", "ilang huta dison",
    "alai pileh", "kija alangan", "kemma battu", "keng gun edimma",
    # Lupa naruh / simpan
    "lupa naro", "lupa naruh", "lupa nataro", "lupa taro", "lupa taruh", "lupa ditaruh",
    "lupa meletakkan", "lupa nyimpen", "lupa nyimpan", "lupa menyimpan",
    "lupa simpen dimana", "lupa taro dimana", "lupa naro dimana", "lupa naruh dimana",
    # Konfirmasi / kelihatan
    "ada yang liat", "ada yang lihat", "ada yg liat", "ada yg lihat", "ada yang nemu",
    "nemu", "nampak", "kelihatan", "keliatan", "kliatan", "keliatan gak", "keliatan ga",
}

FILLER_WORDS: set[str] = {
    "saya punya", "aku punya", "punya saya", "punya aku", "punya gue", "punya gua",
    "punya ane", "punyanya", "punyaku", "saya", "aku", "gue", "gua", "gw", "ane",
    "kamu", "kau", "anda", "ku", "mu", "nya", "bentar ya", "sebentar", "bentar",
    "tolong", "yaudah", "please", "dong", "deh", "nih", "tuh", "sih", "ya", "kah",
    "tah", "kek", "lah", "pun", "dulu", "woy", "woi", "eh", "nah", "kok", "toh",
    "kan", "loh", "lho", "lo", "gitu", "gini", "aja", "saja", "juga", "napa",
    "plis", "yuk", "udah", "gan", "bro", "sis", "cuy", "kayaknya", "yah", "banget",
    "coba", "anu", "mmm", "eee", "e", "je", "rek", "atuh", "euy", "teh", "mah",
    "dah", "noh", "yee", "bang", "pole",
}

# =========================================================================
# 1. COLOR_MAP
# =========================================================================
COLOR_MAP: dict[str, str] = {
    # --- Warna dasar ---
    "merah": "red",
    "biru": "blue",
    "hijau": "green",
    "kuning": "yellow",
    "hitam": "black",
    "putih": "white",
    "cokelat": "brown",
    "coklat": "brown",
    "abu-abu": "gray",
    "abu abu": "gray",
    "abuabu": "gray",
    "pink": "pink",
    "merah muda": "pink",
    "ungu": "purple",
    "violet": "violet",
    "oranye": "orange",
    "jingga": "orange",
    "emas": "gold",
    "keemasan": "gold",
    "perak": "silver",
    "keperakan": "silver",
    "krem": "cream",
    "biru dongker": "navy blue",
    "biru donker": "navy blue",
    "navy": "navy blue",
    "maroon": "maroon",
    "marun": "maroon",
    "turquoise": "turquoise",
    "tosca": "turquoise",
    "toska": "turquoise",
    "magenta": "magenta",
    "beige": "beige",
    "khaki": "khaki",
    "lavender": "lavender",
    "lavendel": "lavender",
    "peach": "peach",
    "salem": "salmon",
    "salmon": "salmon",
    "indigo": "indigo",

    # --- Variasi / nuansa merah ---
    "merah tua": "dark red",
    "merah cerah": "bright red",
    "merah menyala": "bright red",
    "merah marun": "maroon",
    "merah bata": "brick red",
    "merah delima": "ruby red",
    "merah anggur": "wine red",
    "merah muda pucat": "pale pink",

    # --- Variasi / nuansa biru ---
    "biru muda": "light blue",
    "biru tua": "dark blue",
    "biru langit": "sky blue",
    "biru laut": "sea blue",
    "biru navy": "navy blue",
    "biru dongker tua": "dark navy blue",
    "biru toska": "turquoise blue",
    "biru elektrik": "electric blue",
    "biru pastel": "pastel blue",

    # --- Variasi / nuansa hijau ---
    "hijau daun": "leaf green",
    "hijau tua": "dark green",
    "hijau muda": "light green",
    "hijau lumut": "moss green",
    "hijau army": "army green",
    "hijau tentara": "army green",
    "hijau toska": "turquoise green",
    "hijau botol": "bottle green",
    "hijau mint": "mint green",
    "hijau pastel": "pastel green",
    "hijau zaitun": "olive green",

    # --- Variasi / nuansa kuning ---
    "kuning kunyit": "turmeric yellow",
    "kuning cerah": "bright yellow",
    "kuning pucat": "pale yellow",
    "kuning emas": "golden yellow",
    "kuning mustard": "mustard yellow",
    "kuning pastel": "pastel yellow",
    "kuning gading": "ivory yellow",

    # --- Variasi / nuansa hitam ---
    "hitam pekat": "jet black",
    "hitam legam": "jet black",
    "hitam doff": "matte black",
    "hitam mengkilap": "glossy black",
    "hitam kelam": "deep black",

    # --- Variasi / nuansa putih ---
    "putih tulang": "bone white",
    "putih gading": "ivory white",
    "putih susu": "milk white",
    "putih bersih": "clean white",
    "putih mutiara": "pearl white",
    "putih salju": "snow white",

    # --- Variasi / nuansa abu-abu ---
    "abu-abu muda": "light gray",
    "abu-abu tua": "dark gray",
    "abu-abu gelap": "dark gray",
    "abu-abu terang": "light gray",
    "abu-abu tikus": "mouse gray",
    "abu-abu metalik": "metallic gray",

    # --- Variasi / nuansa cokelat ---
    "cokelat tua": "dark brown",
    "cokelat muda": "light brown",
    "cokelat kayu": "wood brown",
    "cokelat susu": "milk chocolate brown",
    "cokelat karamel": "caramel brown",
    "cokelat tanah": "earth brown",

    # --- Variasi / nuansa ungu ---
    "ungu tua": "dark purple",
    "ungu muda": "light purple",
    "ungu pastel": "pastel purple",
    "ungu terong": "eggplant purple",

    # --- Variasi / nuansa pink ---
    "pink tua": "dark pink",
    "pink muda": "light pink",
    "pink pastel": "pastel pink",
    "pink fanta": "hot pink",
    "pink cerah": "hot pink",

    # --- Variasi / nuansa oranye ---
    "oranye tua": "dark orange",
    "oranye muda": "light orange",
    "oranye pastel": "pastel orange",

    # --- Pola / deskriptor umum ---
    "garis-garis": "striped",
    "garis garis": "striped",
    "bergaris": "striped",
    "kotak-kotak": "checkered",
    "kotak kotak": "checkered",
    "berkotak": "checkered",
    "polkadot": "polka dot",
    "polka dot": "polka dot",
    "totol-totol": "polka dot",
    "bintik-bintik": "spotted",
    "polos": "plain",
    "bermotif": "patterned",
    "motif bunga": "floral pattern",
    "bermotif bunga": "floral pattern",
    "motif batik": "batik pattern",
    "transparan": "transparent",
    "bening": "clear",
    "gelap": "dark",
    "terang": "light",
    "cerah": "bright",
    "mengkilap": "glossy",
    "berkilau": "shiny",
    "doff": "matte",
    "kusam": "dull",
    "metalik": "metallic",
    "pelangi": "rainbow",
    "warna-warni": "colorful",
    "warni warni": "colorful",
    "multiwarna": "multicolor",
    "pastel": "pastel",
    "kamuflase": "camouflage",
    "loreng": "camouflage",
    "gradasi": "gradient",
    "bermotif kotak": "checkered pattern",
    "bermotif garis": "striped pattern",
    "berbintik": "spotted",
    "bercorak": "patterned",
    "polos tanpa motif": "plain solid",
    "muda": "light",
    "tua": "dark",
    "pudar": "faded",
    "kalem": "muted",
    "soft": "soft",
    "nude": "nude",
    "denim": "denim blue",
    "abu-abu semen": "cement gray",
    "biru pudar": "faded blue",
    "terang benderang": "very bright",
    "silver": "silver",
    "gold": "gold",
    "cream": "cream",
    "off white": "off white",
    "putih gading tua": "dark ivory white",
    "hitam kusam": "dull black",
    "cerah menyala": "vivid bright",
    "corak macan": "tiger print",
    "corak zebra": "zebra print",
    "corak ular": "snake print",
    "motif kotak-kotak besar": "large checkered pattern",
}


# =========================================================================
# 2. EXTRA_ID_TO_EN
# =========================================================================
EXTRA_ID_TO_EN: dict[str, str] = {
    # --- Barang pribadi ---
    "dompet": "wallet",
    "hp": "cell phone",
    "handphone": "cell phone",
    "hape": "cell phone",
    "telepon genggam": "cell phone",
    "telepon seluler": "cell phone",
    "ponsel": "cell phone",
    "smartphone": "cell phone",
    "gawai": "cell phone",
    "kunci": "key",
    "anak kunci": "key",
    "kunci motor": "key",
    "kunci mobil": "key",
    "gembok": "padlock",
    "kacamata": "glasses",
    "kacamata baca": "reading glasses",
    "kacamata hitam": "sunglasses",
    "kartu": "card",
    "kartu identitas": "id card",
    "ktp": "id card",
    "kartu nama": "business card",
    "kartu kredit": "credit card",
    "kartu debit": "debit card",
    "kartu atm": "atm card",
    "jam": "clock",
    "jam tangan": "watch",
    "cincin": "ring",
    "gelang": "bracelet",
    "kalung": "necklace",
    "anting": "earring",
    "anting-anting": "earring",
    "dasi": "necktie",
    "ikat pinggang": "belt",
    "sabuk": "belt",
    "dompet koin": "coin purse",
    "buku tabungan": "bank passbook",

    # --- Barang rumah tangga ---
    "botol": "bottle",
    "botol minum": "water bottle",
    "botol air": "water bottle",
    "gelas": "glass",
    "cangkir": "cup",
    "mug": "mug",
    "piring": "plate",
    "mangkuk": "bowl",
    "sendok": "spoon",
    "garpu": "fork",
    "pisau": "knife",
    "pisau dapur": "kitchen knife",
    "remote": "remote control",
    "remot": "remote control",
    "remote tv": "tv remote control",
    "remot tv": "tv remote control",
    "remote ac": "ac remote control",
    "charger": "charger",
    "cas": "charger",
    "pengisi daya": "charger",
    "kabel": "cable",
    "kabel data": "data cable",
    "gunting": "scissors",
    "sisir": "comb",
    "sikat gigi": "toothbrush",
    "pasta gigi": "toothpaste",
    "handuk": "towel",
    "sabun": "soap",
    "sabun batang": "bar soap",
    "tisu": "tissue",
    "tisu basah": "wet wipes",
    "korek api": "lighter",
    "lilin": "candle",
    "senter": "flashlight",
    "baterai": "battery",
    "termos": "thermos",
    "panci": "pot",
    "wajan": "frying pan",
    "ember": "bucket",
    "sapu": "broom",
    "kemoceng": "feather duster",
    "vas bunga": "flower vase",
    "bantal": "pillow",
    "guling": "bolster",
    "selimut": "blanket",
    "kasur": "mattress",
    "keset": "doormat",
    "gantungan baju": "clothes hanger",
    "jepitan baju": "clothespin",

    # --- Pakaian / aksesoris ---
    "tas": "bag",
    "tas ransel": "backpack",
    "ransel": "backpack",
    "tas selempang": "sling bag",
    "tas tangan": "handbag",
    "koper": "suitcase",
    "sepatu": "shoes",
    "sepatu boot": "boots",
    "sandal": "sandals",
    "sandal jepit": "flip flops",
    "topi": "hat",
    "topi baseball": "baseball cap",
    "jaket": "jacket",
    "mantel": "coat",
    "payung": "umbrella",
    "kaos": "t-shirt",
    "kaus": "t-shirt",
    "kemeja": "shirt",
    "celana": "pants",
    "celana panjang": "pants",
    "celana pendek": "shorts",
    "rok": "skirt",
    "sarung tangan": "gloves",
    "masker": "mask",
    "syal": "scarf",
    "kaos kaki": "socks",
    "kaus kaki": "socks",

    # --- Furnitur / elektronik ---
    "kursi": "chair",
    "meja": "table",
    "lemari": "cabinet",
    "lemari baju": "wardrobe",
    "rak buku": "bookshelf",
    "saklar": "light switch",
    "saklar lampu": "light switch",
    "stop kontak": "power outlet",
    "colokan": "power outlet",
    "colokan listrik": "power outlet",
    "pintu": "door",
    "jendela": "window",
    "tv": "television",
    "televisi": "television",
    "laptop": "laptop",
    "komputer": "computer",
    "keyboard": "keyboard",
    "mouse": "mouse",
    "printer": "printer",
    "kipas angin": "electric fan",
    "ac": "air conditioner",
    "pendingin ruangan": "air conditioner",
    "lampu": "lamp",
    "lampu meja": "table lamp",
    "speaker": "speaker",
    "pengeras suara": "speaker",
    "radio": "radio",
    "kompor": "stove",
    "kulkas": "refrigerator",
    "lemari es": "refrigerator",
    "microwave": "microwave",
    "rice cooker": "rice cooker",
    "penanak nasi": "rice cooker",
    "setrika": "iron",

    # --- Benda umum sehari-hari lainnya ---
    "buku": "book",
    "pena": "pen",
    "bolpoin": "pen",
    "pensil": "pencil",
    "penghapus": "eraser",
    "penggaris": "ruler",
    "kertas": "paper",
    "amplop": "envelope",
    "stapler": "stapler",
    "hekter": "stapler",
    "lem": "glue",
    "selotip": "tape",
    "kalkulator": "calculator",
    "bola": "ball",
    "cermin": "mirror",
    "jam dinding": "wall clock",
    "tanaman": "plant",
    "pot bunga": "flower pot",
    "tongkat": "cane",
    "tongkat tunanetra": "white cane",

    # --- Makanan & minuman ---
    "nasi kotak": "lunch box",
    "kotak makan": "lunch box",
    "botol kecap": "sauce bottle",
    "kaleng": "can",
    "kaleng soda": "soda can",
    "kaleng minuman": "soda can",
    "sachet kopi": "coffee sachet",
    "roti": "bread",
    "roti tawar": "sliced bread",
    "apel": "apple",
    "pisang": "banana",
    "jeruk": "orange fruit",
    "semangka": "watermelon",
    "mangga": "mango",
    "anggur": "grapes",
    "nanas": "pineapple",
    "pepaya": "papaya",
    "alpukat": "avocado",
    "wortel": "carrot",
    "tomat": "tomato",
    "kentang": "potato",
    "bawang": "onion",
    "bawang merah": "shallot",
    "bawang putih": "garlic",
    "cabai": "chili pepper",
    "cabe": "chili pepper",
    "telur": "egg",
    "susu kotak": "milk carton",
    "susu kaleng": "canned milk",
    "air mineral gelas": "cup water",
    "air mineral botol": "mineral water bottle",
    "gelas plastik": "plastic cup",
    "mie instan": "instant noodles",
    "permen": "candy",
    "snack": "snack pack",
    "biskuit": "biscuit pack",
    "teko": "kettle",
    "dispenser galon": "water dispenser",
    "galon air": "water gallon",
    "nampan": "tray",
    "sedotan": "straw",
    "tisu makan": "napkin",
    "tempat tisu": "tissue box",
    "sendok plastik": "plastic spoon",
    "garpu plastik": "plastic fork",
    "cangkir kopi": "coffee cup",

    # --- Alat tulis & kantor tambahan ---
    "folder": "folder",
    "buku catatan": "notebook",
    "spidol": "marker",
    "tipe-x": "correction fluid",
    "tipe x": "correction fluid",
    "paper clip": "paper clip",
    "klip kertas": "paper clip",
    "binder clip": "binder clip",
    "post-it": "sticky notes",
    "papan tulis": "whiteboard",
    "whiteboard": "whiteboard",

    # --- Elektronik tambahan ---
    "earphone": "earphones",
    "headphone": "headphones",
    "headset": "headset",
    "powerbank": "power bank",
    "flashdisk": "usb flash drive",
    "hardisk": "hard drive",
    "harddisk": "hard drive",
    "kamera": "camera",
    "tripod": "tripod",
    "drone": "drone",
    "proyektor": "projector",
    "router wifi": "wifi router",
    "modem": "modem",
    "mesin fax": "fax machine",
    "mesin fotocopy": "photocopier",
    "walkie talkie": "walkie talkie",
    "jam alarm": "alarm clock",
    "timbangan badan": "bathroom scale",
    "timbangan dapur": "kitchen scale",

    # --- Kendaraan & terkait ---
    "motor": "motorcycle",
    "sepeda motor": "motorcycle",
    "mobil": "car",
    "sepeda": "bicycle",
    "helm": "helmet",
    "spion": "side mirror",
    "plat nomor": "license plate",
    "ban": "tire",
    "knalpot": "exhaust pipe",
    "jerigen": "jerrycan",

    # --- Alat kebersihan tambahan ---
    "pel": "mop",
    "vacuum cleaner": "vacuum cleaner",
    "tempat sampah": "trash can",
    "kantong plastik": "plastic bag",
    "spons cuci piring": "dish sponge",
    "sabun cuci piring": "dish soap",
    "deterjen": "detergent",
    "pengharum ruangan": "air freshener",

    # --- Alat masak tambahan ---
    "talenan": "cutting board",
    "parutan": "grater",
    "saringan": "strainer",
    "spatula": "spatula",
    "sutil": "spatula",
    "teflon": "non-stick pan",
    "blender": "blender",
    "toaster": "toaster",
    "oven": "oven",

    # --- Kamar mandi ---
    "shampoo": "shampoo bottle",
    "sabun cair": "liquid soap",
    "sikat wc": "toilet brush",
    "gayung": "dipper",
    "ember mandi": "bathroom bucket",
    "tempat sabun": "soap dish",
    "hair dryer": "hair dryer",

    # --- Perlengkapan bayi & hewan peliharaan ---
    "botol susu bayi": "baby bottle",
    "dot": "pacifier",
    "popok": "diaper",
    "stroller": "stroller",
    "kereta bayi": "stroller",
    "mainan anak": "toy",
    "mangkuk makanan hewan": "pet bowl",
    "kandang hewan": "pet cage",
    "tali anjing": "dog leash",
    "kalung hewan": "pet collar",

    # --- Olahraga ---
    "raket": "racket",
    "bola basket": "basketball",
    "bola sepak": "soccer ball",
    "matras yoga": "yoga mat",
    "dumbbell": "dumbbell",
    "skateboard": "skateboard",

    # --- Perkakas / pertukangan ---
    "obeng": "screwdriver",
    "palu": "hammer",
    "tang": "pliers",
    "bor": "drill",
    "meteran": "tape measure",
    "paku": "nail",
    "baut": "bolt",

    # --- Uang & pembayaran ---
    "uang kertas": "banknote",
    "uang koin": "coin",

    # --- Alat musik ---
    "gitar": "guitar",
    "piano": "piano",
    "drum": "drum",
    "biola": "violin",
    "mikrofon": "microphone",

    # --- Perlengkapan medis ---
    "termometer": "thermometer",
    "tensimeter": "blood pressure monitor",
    "obat": "medicine bottle",
    "plester": "adhesive bandage",
    "kotak p3k": "first aid kit",
}


# =========================================================================
# 3. EXTRA_HEIGHTS_CM
# =========================================================================
EXTRA_HEIGHTS_CM: dict[str, int] = {
    # --- Barang pribadi ---
    "wallet": 10,
    "cell phone": 15,
    "key": 6,
    "padlock": 5,
    "glasses": 14,
    "reading glasses": 14,
    "sunglasses": 14,
    "card": 6,
    "id card": 9,
    "business card": 5,
    "credit card": 6,
    "debit card": 6,
    "atm card": 6,
    "clock": 25,
    "watch": 4,
    "ring": 2,
    "bracelet": 7,
    "necklace": 35,
    "earring": 2,
    "necktie": 130,
    "belt": 100,
    "coin purse": 10,
    "bank passbook": 15,

    # --- Barang rumah tangga ---
    "bottle": 25,
    "water bottle": 22,
    "glass": 12,
    "cup": 9,
    "mug": 10,
    "plate": 25,
    "bowl": 10,
    "spoon": 15,
    "fork": 18,
    "knife": 20,
    "kitchen knife": 25,
    "remote control": 18,
    "tv remote control": 20,
    "ac remote control": 18,
    "charger": 6,
    "data cable": 100,
    "cable": 100,
    "scissors": 18,
    "comb": 17,
    "toothbrush": 18,
    "toothpaste": 16,
    "towel": 70,
    "soap": 7,
    "bar soap": 7,
    "tissue": 12,
    "wet wipes": 10,
    "lighter": 8,
    "candle": 15,
    "flashlight": 15,
    "battery": 5,
    "thermos": 25,
    "pot": 20,
    "frying pan": 5,
    "bucket": 30,
    "broom": 130,
    "feather duster": 40,
    "flower vase": 25,
    "pillow": 45,
    "bolster": 100,
    "blanket": 150,
    "mattress": 20,
    "doormat": 2,
    "clothes hanger": 20,
    "clothespin": 7,

    # --- Pakaian / aksesoris ---
    "bag": 35,
    "backpack": 45,
    "sling bag": 25,
    "handbag": 25,
    "suitcase": 60,
    "shoes": 12,
    "boots": 30,
    "sandals": 5,
    "flip flops": 3,
    "hat": 15,
    "baseball cap": 15,
    "jacket": 65,
    "coat": 100,
    "umbrella": 90,
    "t-shirt": 70,
    "shirt": 75,
    "pants": 105,
    "shorts": 45,
    "skirt": 55,
    "gloves": 25,
    "mask": 15,
    "scarf": 150,
    "socks": 25,

    # --- Furnitur / elektronik ---
    "chair": 90,
    "table": 75,
    "cabinet": 150,
    "wardrobe": 180,
    "bookshelf": 180,
    "light switch": 8,
    "power outlet": 8,
    "door": 200,
    "window": 120,
    "television": 60,
    "laptop": 25,
    "computer": 45,
    "keyboard": 4,
    "mouse": 4,
    "printer": 25,
    "electric fan": 100,
    "air conditioner": 35,
    "lamp": 40,
    "table lamp": 40,
    "speaker": 30,
    "radio": 20,
    "stove": 15,
    "refrigerator": 170,
    "microwave": 30,
    "rice cooker": 25,
    "iron": 15,

    # --- Benda umum sehari-hari lainnya ---
    "book": 25,
    "pen": 15,
    "pencil": 18,
    "eraser": 3,
    "ruler": 3,
    "paper": 30,
    "envelope": 12,
    "stapler": 5,
    "glue": 12,
    "tape": 5,
    "calculator": 15,
    "ball": 22,
    "mirror": 60,
    "wall clock": 25,
    "plant": 40,
    "flower pot": 20,
    "cane": 90,
    "white cane": 130,

    # --- Makanan & minuman ---
    "lunch box": 8,
    "sauce bottle": 20,
    "can": 12,
    "soda can": 12,
    "coffee sachet": 12,
    "bread": 12,
    "sliced bread": 12,
    "apple": 8,
    "banana": 18,
    "orange fruit": 7,
    "watermelon": 25,
    "mango": 10,
    "grapes": 15,
    "pineapple": 25,
    "papaya": 20,
    "avocado": 10,
    "carrot": 18,
    "tomato": 6,
    "potato": 7,
    "onion": 6,
    "shallot": 4,
    "garlic": 4,
    "chili pepper": 8,
    "egg": 6,
    "milk carton": 20,
    "canned milk": 10,
    "cup water": 7,
    "mineral water bottle": 25,
    "plastic cup": 10,
    "instant noodles": 10,
    "candy": 3,
    "snack pack": 20,
    "biscuit pack": 15,
    "kettle": 22,
    "water dispenser": 100,
    "water gallon": 45,
    "tray": 3,
    "straw": 20,
    "napkin": 15,
    "tissue box": 12,
    "plastic spoon": 15,
    "plastic fork": 18,
    "coffee cup": 9,

    # --- Alat tulis & kantor tambahan ---
    "folder": 30,
    "notebook": 21,
    "marker": 14,
    "correction fluid": 8,
    "paper clip": 3,
    "binder clip": 3,
    "sticky notes": 8,
    "whiteboard": 60,

    # --- Elektronik tambahan ---
    "earphones": 4,
    "headphones": 18,
    "headset": 18,
    "power bank": 10,
    "usb flash drive": 5,
    "hard drive": 12,
    "camera": 10,
    "tripod": 100,
    "drone": 15,
    "projector": 15,
    "wifi router": 5,
    "modem": 5,
    "fax machine": 25,
    "photocopier": 100,
    "walkie talkie": 20,
    "alarm clock": 12,
    "bathroom scale": 3,
    "kitchen scale": 5,

    # --- Kendaraan & terkait ---
    "motorcycle": 110,
    "car": 150,
    "bicycle": 100,
    "helmet": 28,
    "side mirror": 15,
    "license plate": 15,
    "tire": 60,
    "exhaust pipe": 10,
    "jerrycan": 35,

    # --- Alat kebersihan tambahan ---
    "mop": 130,
    "vacuum cleaner": 110,
    "trash can": 50,
    "plastic bag": 30,
    "dish sponge": 4,
    "dish soap": 20,
    "detergent": 25,
    "air freshener": 20,

    # --- Alat masak tambahan ---
    "cutting board": 30,
    "grater": 20,
    "strainer": 15,
    "spatula": 30,
    "non-stick pan": 5,
    "blender": 35,
    "toaster": 20,
    "oven": 35,

    # --- Kamar mandi ---
    "shampoo bottle": 20,
    "liquid soap": 18,
    "toilet brush": 40,
    "dipper": 15,
    "bathroom bucket": 25,
    "soap dish": 3,
    "hair dryer": 22,

    # --- Perlengkapan bayi & hewan peliharaan ---
    "baby bottle": 18,
    "pacifier": 6,
    "diaper": 25,
    "stroller": 100,
    "toy": 15,
    "pet bowl": 6,
    "pet cage": 40,
    "dog leash": 100,
    "pet collar": 3,

    # --- Olahraga ---
    "racket": 68,
    "basketball": 24,
    "soccer ball": 22,
    "yoga mat": 3,
    "dumbbell": 20,
    "skateboard": 12,

    # --- Perkakas / pertukangan ---
    "obeng": 20,
    "hammer": 30,
    "pliers": 20,
    "drill": 25,
    "tape measure": 6,
    "nail": 5,
    "bolt": 3,

    # --- Uang & pembayaran ---
    "banknote": 7,
    "coin": 2,

    # --- Alat musik ---
    "guitar": 100,
    "piano": 100,
    "drum": 40,
    "violin": 60,
    "microphone": 20,

    # --- Perlengkapan medis ---
    "thermometer": 15,
    "blood pressure monitor": 10,
    "medicine bottle": 8,
    "adhesive bandage": 5,
    "first aid kit": 15,
}
